# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O2O', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='eventenddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
