# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('O2O', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='height',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='left',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='top',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='width',
        ),
    ]
