# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O2O', '0002_poster_eventenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='eventplace',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
