# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('O2O', '0002_auto_20171127_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='O2O.User'),
        ),
    ]
