# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O2O', '0003_poster_eventplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='eventholder',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
